export enum OrderPaymentMethod {
  COD = 'COD',
  CARD = 'CARD',
}

export enum OrderPaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  COLLECTED = 'COLLECTED',
  FAILED = 'FAILED',
}

export enum SubOrderFulfillmentStatus {
  AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  PACKED = 'PACKED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}

export enum OrderEventType {
  STATUS_CHANGED = 'STATUS_CHANGED',
  PAYMENT_COLLECTED = 'PAYMENT_COLLECTED',
  DELIVERED_BY_BUYER = 'DELIVERED_BY_BUYER',
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  RETURN_APPROVED = 'RETURN_APPROVED',
  RETURN_REJECTED = 'RETURN_REJECTED',
  RETURN_SHIPPED_BACK = 'RETURN_SHIPPED_BACK',
  RETURN_RECEIVED = 'RETURN_RECEIVED',
  RETURN_REFUNDED = 'RETURN_REFUNDED',
  RETURN_CLOSED = 'RETURN_CLOSED',
}
