export enum OrderPaymentMethod {
  COD = 'COD',
}

export enum OrderPaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  COLLECTED = 'COLLECTED',
  FAILED = 'FAILED',
}

export enum SubOrderFulfillmentStatus {
  AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  PACKED = 'PACKED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}

export enum OrderEventType {
  STATUS_CHANGED = 'STATUS_CHANGED',
  PAYMENT_COLLECTED = 'PAYMENT_COLLECTED',
  DELIVERED_BY_BUYER = 'DELIVERED_BY_BUYER',
}
