export enum ReturnStatus {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  SHIPPED_BACK = 'SHIPPED_BACK',
  RECEIVED = 'RECEIVED',
  REFUNDED = 'REFUNDED',
  CLOSED = 'CLOSED',
  REJECTED = 'REJECTED',
}

export enum ReturnReason {
  NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
  DAMAGED = 'DAMAGED',
  WRONG_ITEM = 'WRONG_ITEM',
  ARRIVED_LATE = 'ARRIVED_LATE',
  NO_LONGER_NEEDED = 'NO_LONGER_NEEDED',
  OTHER = 'OTHER',
}
