export enum KycDocumentType {
  COMMERCIAL_REGISTRATION = 'COMMERCIAL_REGISTRATION',
  TAX_CERTIFICATE = 'TAX_CERTIFICATE',
  IBAN_DOCUMENT = 'IBAN_DOCUMENT',
  OWNER_ID = 'OWNER_ID',
}

export enum KycDocumentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum KycStatus {
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
